name: Render 04_Final_model Notebook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install jupyter nbconvert \
                      pandas numpy matplotlib scipy \
                      seaborn scikit-learn statsmodels \
                      xgboost lightgbm optuna torch \
                      requests joblib

      - name: Convert 04_Final_model.ipynb to HTML
        if: false
        run: |
          jupyter nbconvert "notebooks/04_Final_model.ipynb" \
            --to html \
            --output "notebooks/04_Final_model.html" \
            --ExecutePreprocessor.timeout=-1 \
            --execute

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: 04_Final_model-html
          path: notebooks/04_Final_model.html
